### ISSUE TITLE
Activity icon

### ISSUE THREAD

**Issue by moodledev** [stefanscholz/moodle-mod_typorepo#2]

**Comment by moodledev** [comment]
![mod_typorepo_pix_icon](https://user-images.githubusercontent.com/46829091/72366042-13f99a80-36bf-11ea-8969-5dd2052bc116.gif)

1. Existing icon is small.
2. Should we use Typo3's logo?

**Comment by stefanscholz** [comment]
I've asked the customer. Probably for now, yes. I'll update this issue once I know.
