### ISSUE TITLE
Selected content not found – 404

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-mod_typorepo#5]
I’ve now added ssl to https://lms3.bdecent.de/

It seems to be possible to select a learning content now:

<img width="993" alt="Bildschirmfoto 2020-01-19 um 17 58 36" src="https://user-images.githubusercontent.com/3414705/72684975-992ce700-3ae5-11ea-9263-16a94ab144e9.png">

But the iframe src seems to miss the base url and the id of the content:

<iframe style="margin-left: 0px;" src="&amp;token=64226881ee5abdbc8266cdbc3e7dcb2c&amp;time=1579453131&amp;moodlemodid=2&amp;login=YmRhZG1pbg==&amp;firstname=QWRtaW4=&amp;lastname=VXNlcg==&amp;courseid=2&amp;email=c3RzQGJkZWNlbnQuZGU=" frameborder="0" scrolling="auto" width="100%" height="500"> </iframe>

Can you please have a look?

**Comment by moodledev** [comment]
I can't test the fix since I'm still blocked from accessing typo3. Please  try it and let me know

**Comment by stefanscholz** [comment]
The customer has told me that they do not block IP addresses. Why do you think that you are blocked? I.e. how do you see that?

**Comment by moodledev** [comment]
The screenshot you posted above confirms the plugins work, but my dev Moodle always displays this: 
![image](https://user-images.githubusercontent.com/46829091/72821745-968dd700-3c36-11ea-9d69-be0dcd0aa2cb.png)

**Comment by stefanscholz** [comment]
The issue remains unfortunately – the iframe still has an incomplete src.
<iframe style="margin-left: 0px;" src="&amp;token=2dc3b6006a06a1b1fc58f7b5e0e8e4f4&amp;time=1579623143&amp;moodlemodid=5&amp;login=YmRhZG1pbg==&amp;firstname=QWRtaW4=&amp;lastname=VXNlcg==&amp;courseid=2&amp;email=c3RzQGJkZWNlbnQuZGU=" frameborder="0" scrolling="" width="100%" height=""> </iframe>

**Comment by moodledev** [comment]
This is frustrating not being able to test. Please try it again on your site

**Comment by stefanscholz** [comment]
Brilliant, seems to work! Many thanks!
Will continue testing and then close this issue.
