### ISSUE TITLE
Coding Error

### ISSUE THREAD

**Issue by stefanscholz** [stefanscholz/moodle-mod_typorepo#9]
Coding error detected, it must be fixed by a programmer: Invalid state passed to moodle_page::set_state. We are in state 3 and state 3 was requested.

<img width="1627" alt="Bildschirmfoto 2020-01-23 um 23 02 34" src="https://user-images.githubusercontent.com/3414705/73027820-7297e480-3e34-11ea-998d-047769f5c7ca.png">

**Comment by moodledev** [comment]
Is there a different error message with debugging turned on?

**Comment by stefanscholz** [comment]
Yes, sorry, should have sent them right away:


Some HTML tags were opened in the body of the page but not closed.

Open header/footer at:
line 2515 of /lib/outputlib.php: call to xhtml_container_stack->log()
line 1345 of /lib/outputrenderers.php: call to xhtml_container_stack->push()
line 1941 of /lib/setuplib.php: call to core_renderer->header()
line 77 of /mod/typorepo/view.php: call to bootstrap_renderer->__call()
Close header/footer at:
line 2543 of /lib/outputlib.php: call to xhtml_container_stack->log()
line 1398 of /lib/outputrenderers.php: call to xhtml_container_stack->pop()
line 82 of /mod/typorepo/view.php: call to core_renderer->footer()
line 2560 of /lib/outputlib.php: call to debugging()
line 1443 of /lib/outputrenderers.php: call to xhtml_container_stack->pop_all_but_last()
line 1396 of /lib/outputrenderers.php: call to core_renderer->container_end_all()
line 84 of /mod/typorepo/view.php: call to core_renderer->footer()
There are no more open containers. This suggests there is a nesting problem.

Open header/footer at:
line 2515 of /lib/outputlib.php: call to xhtml_container_stack->log()
line 1345 of /lib/outputrenderers.php: call to xhtml_container_stack->push()
line 1941 of /lib/setuplib.php: call to core_renderer->header()
line 77 of /mod/typorepo/view.php: call to bootstrap_renderer->__call()
Close header/footer at:
line 2543 of /lib/outputlib.php: call to xhtml_container_stack->log()
line 1398 of /lib/outputrenderers.php: call to xhtml_container_stack->pop()
line 82 of /mod/typorepo/view.php: call to core_renderer->footer()
line 2531 of /lib/outputlib.php: call to debugging()
line 1398 of /lib/outputrenderers.php: call to xhtml_container_stack->pop()
line 84 of /mod/typorepo/view.php: call to core_renderer->footer()
Some HTML tags were opened in the body of the page but not closed.

Open header/footer at:
line 2515 of /lib/outputlib.php: call to xhtml_container_stack->log()
line 1345 of /lib/outputrenderers.php: call to xhtml_container_stack->push()
line 1941 of /lib/setuplib.php: call to core_renderer->header()
line 77 of /mod/typorepo/view.php: call to bootstrap_renderer->__call()
Close header/footer at:
line 2543 of /lib/outputlib.php: call to xhtml_container_stack->log()
line 1398 of /lib/outputrenderers.php: call to xhtml_container_stack->pop()
line 82 of /mod/typorepo/view.php: call to core_renderer->footer()
Open box at:
line 2515 of /lib/outputlib.php: call to xhtml_container_stack->log()
line 3077 of /lib/outputrenderers.php: call to xhtml_container_stack->push()
line 3065 of /lib/outputrenderers.php: call to core_renderer->box_start()
line 2817 of /lib/outputrenderers.php: call to core_renderer->box()
line 386 of /lib/setuplib.php: call to core_renderer->fatal_error()
line ? of unknownfile: call to default_exception_handler()
Close box at:
line 2543 of /lib/outputlib.php: call to xhtml_container_stack->log()
line 3089 of /lib/outputrenderers.php: call to xhtml_container_stack->pop()
line 3065 of /lib/outputrenderers.php: call to core_renderer->box_end()
line 2817 of /lib/outputrenderers.php: call to core_renderer->box()
line 386 of /lib/setuplib.php: call to core_renderer->fatal_error()
line ? of unknownfile: call to default_exception_handler()
line 2560 of /lib/outputlib.php: call to debugging()
line 1443 of /lib/outputrenderers.php: call to xhtml_container_stack->pop_all_but_last()
line 1396 of /lib/outputrenderers.php: call to core_renderer->container_end_all()
line 2843 of /lib/outputrenderers.php: call to core_renderer->footer()
line 386 of /lib/setuplib.php: call to core_renderer->fatal_error()
line ? of unknownfile: call to default_exception_handler()
There are no more open containers. This suggests there is a nesting problem.

Open header/footer at:
line 2515 of /lib/outputlib.php: call to xhtml_container_stack->log()
line 1345 of /lib/outputrenderers.php: call to xhtml_container_stack->push()
line 1941 of /lib/setuplib.php: call to core_renderer->header()
line 77 of /mod/typorepo/view.php: call to bootstrap_renderer->__call()
Close header/footer at:
line 2543 of /lib/outputlib.php: call to xhtml_container_stack->log()
line 1398 of /lib/outputrenderers.php: call to xhtml_container_stack->pop()
line 82 of /mod/typorepo/view.php: call to core_renderer->footer()
Open box at:
line 2515 of /lib/outputlib.php: call to xhtml_container_stack->log()
line 3077 of /lib/outputrenderers.php: call to xhtml_container_stack->push()
line 3065 of /lib/outputrenderers.php: call to core_renderer->box_start()
line 2817 of /lib/outputrenderers.php: call to core_renderer->box()
line 386 of /lib/setuplib.php: call to core_renderer->fatal_error()
line ? of unknownfile: call to default_exception_handler()
Close box at:
line 2543 of /lib/outputlib.php: call to xhtml_container_stack->log()
line 3089 of /lib/outputrenderers.php: call to xhtml_container_stack->pop()
line 3065 of /lib/outputrenderers.php: call to core_renderer->box_end()
line 2817 of /lib/outputrenderers.php: call to core_renderer->box()
line 386 of /lib/setuplib.php: call to core_renderer->fatal_error()
line ? of unknownfile: call to default_exception_handler()
line 2531 of /lib/outputlib.php: call to debugging()
line 1398 of /lib/outputrenderers.php: call to xhtml_container_stack->pop()
line 2843 of /lib/outputrenderers.php: call to core_renderer->footer()
line 386 of /lib/setuplib.php: call to core_renderer->fatal_error()
line ? of unknownfile: call to default_exception_handler()
Coding error detected, it must be fixed by a programmer: Invalid state passed to moodle_page::set_state. We are in state 3 and state 3 was requested.
Debug info:
Error code: codingerror
Stack trace:
line 980 of /lib/pagelib.php: coding_exception thrown
line 1428 of /lib/outputrenderers.php: call to moodle_page->set_state()
line 84 of /mod/typorepo/view.php: call to core_renderer->footer()
Coding error detected, it must be fixed by a programmer: Invalid state passed to moodle_page::set_state. We are in state 3 and state 3 was requested.
Debug info:
Error code: codingerror
Stack trace:
line 980 of /lib/pagelib.php: coding_exception thrown
line 1428 of /lib/outputrenderers.php: call to moodle_page->set_state()
line 2843 of /lib/outputrenderers.php: call to core_renderer->footer()
line 386 of /lib/setuplib.php: call to core_renderer->fatal_error()
line ? of unknownfile: call to default_exception_handler()

**Comment by moodledev** [comment]
@stefanscholz Thanks!

**Comment by Transazja** [comment]
Exception - Call to undefined function core\task\proc_open()
Coding error detected, it must be fixed by a programmer: Invalid state passed to moodle_page::set_state. We are in state 3 and state 3 was requested.

<img width="1859" height="367" alt="Image" src="https://github.com/user-attachments/assets/50d02241-6309-4424-92c4-cf79a272e66f" />
